### ISSUE TITLE
sd interval bar lengths not comprehensible

### ISSUE THREAD

**Issue by Chr96er** [jaredlander/coefplot#13]
When running the following code, I don't understand the interval bar lengths when comparing with the linear models summary (line 3). E.g. variable `e` has the longest bar, but it doesn't have the highest p-value. Am I missing something or is this a bug?
```require(arm)
sampleDataset = read.csv("http://pastebin.com/raw/qhge6SDY")
#Variable no. 18 is the dependent variable, all others except row number are independent variables
linear_model <- lm(sampleDataset[,18] ~ ., data=sampleDataset[,2:17])
summary(linear_model)
coefplot(linear_model)
```

edit: Upon inspecting the results I just noticed, that the lengths seem to be proportional to the std-error, not the p-value. I understand the reasoning in doing this, but I'm wondering whether the latter would be possible (if (!) reasonable) as well. I.e. that the lengths are proportional to the p-value.

**Comment by jaredlander** [comment]
While computationally that would be easy, basing so much interpretation on p-values is troubling to me.  Aside from always being taught that you shouldn't assume a linearity in p-value meaning the recent [ASA statement](https://www.amstat.org/newsroom/pressreleases/P-ValueStatement.pdf) has really put a damper on p-values.

Now I know that confidence intervals are somewhat similar to p-values, they don't carry the same stigma.

**Comment by Chr96er** [comment]
That makes sense. Thanks for the ASA statement, that was very helpful!
